import type { SeedEventInput } from '@prisma-seed/types';
import { daysFromNow } from '@prisma-seed/utils/date.util';

export function getSeedEvents(): SeedEventInput[] {
  return [
    {
      id: 'seed-event-typescript-meetup',
      title: 'Kyiv TypeScript Meetup: Type-Safe APIs',
      description:
        'Hands-on meetup about end-to-end TypeScript safety with examples from real production projects.',
      dateTime: daysFromNow(5, 19),
      location: 'Kyiv Tech Hub',
      capacity: 2,
      isPublic: true,
      organizerEmail: 'olena@techevents.dev',
      participantEmails: ['max@techevents.dev', 'iryna@techevents.dev'],
      tagSlugs: [
        'technology',
        'typescript',
        'api-design',
        'meetup',
        'community',
      ],
    },
    {
      id: 'seed-event-nestjs-workshop',
      title: 'NestJS in Production Workshop',
      description:
        'Deep-dive workshop on architecture patterns, modules, testing, and performance for NestJS services.',
      dateTime: daysFromNow(8, 18),
      location: 'Lviv IT Cluster Space',
      capacity: 45,
      isPublic: true,
      organizerEmail: 'max@techevents.dev',
      participantEmails: [
        'olena@techevents.dev',
        'denys@techevents.dev',
        'iryna@techevents.dev',
        'viktor@techevents.dev',
        'anna@techevents.dev',
        'dmytro@techevents.dev',
        'sofiia@techevents.dev',
        'andriy@techevents.dev',
        'natalia@techevents.dev',
        'bohdan@techevents.dev',
      ],
      tagSlugs: [
        'technology',
        'nestjs',
        'backend',
        'software-architecture',
        'workshop',
      ],
    },
    {
      id: 'seed-event-prisma-clinic',
      title: 'Prisma + PostgreSQL Performance Clinic',
      description:
        'Session focused on indexing, query optimization, transactions, and schema evolution for high-load apps.',
      dateTime: daysFromNow(12, 17),
      location: 'Dnipro DataLab',
      capacity: 40,
      isPublic: true,
      organizerEmail: 'iryna@techevents.dev',
      participantEmails: [
        'max@techevents.dev',
        'olena@techevents.dev',
        'viktor@techevents.dev',
      ],
      tagSlugs: ['data', 'prisma', 'postgresql', 'sql', 'workshop'],
    },
    {
      id: 'seed-event-react-architecture-night',
      title: 'React 19 Frontend Architecture Night',
      description:
        'Talks and demos about scalable React app structure, routing, data layer patterns, and UI consistency.',
      dateTime: daysFromNow(15, 19),
      location: 'Odesa Frontend Community',
      capacity: 100,
      isPublic: true,
      organizerEmail: 'denys@techevents.dev',
      participantEmails: [
        'olena@techevents.dev',
        'iryna@techevents.dev',
        'max@techevents.dev',
        'viktor@techevents.dev',
        'anna@techevents.dev',
        'dmytro@techevents.dev',
        'sofiia@techevents.dev',
        'andriy@techevents.dev',
        'natalia@techevents.dev',
        'bohdan@techevents.dev',
        'larysa@techevents.dev',
        'kostiantyn@techevents.dev',
        'oksana@techevents.dev',
        'taras@techevents.dev',
        'halyna@techevents.dev',
        'yuriy@techevents.dev',
        'tetiana@techevents.dev',
        'mykola@techevents.dev',
        'olha@techevents.dev',
        'serhiy@techevents.dev',
        'dariya@techevents.dev',
        'roman@techevents.dev',
      ],
      tagSlugs: [
        'technology',
        'react',
        'frontend',
        'software-architecture',
        'conference',
      ],
    },
    {
      id: 'seed-event-devops-essentials',
      title: 'DevOps for Developers: CI/CD Essentials',
      description:
        'Practical event on building reliable pipelines, container workflows, and deployment rollbacks.',
      dateTime: daysFromNow(20, 18),
      location: 'Kharkiv Online Stream',
      capacity: 120,
      isPublic: true,
      organizerEmail: 'olena@techevents.dev',
      participantEmails: [],
      tagSlugs: ['devops', 'ci-cd', 'cloud', 'docker', 'webinar'],
    },
    {
      id: 'seed-event-system-design-mock-interviews',
      title: 'System Design Mock Interviews for Engineers',
      description:
        'Peer-to-peer mock interviews and feedback session around distributed systems and trade-off analysis.',
      dateTime: daysFromNow(25, 18),
      location: 'Remote (Google Meet)',
      capacity: 60,
      isPublic: true,
      organizerEmail: 'max@techevents.dev',
      participantEmails: ['olena@techevents.dev', 'iryna@techevents.dev'],
      tagSlugs: [
        'career',
        'interviewing',
        'system-design',
        'mentoring',
        'education',
      ],
    },
    {
      id: 'seed-event-kubernetes-basics-lab',
      title: 'Kubernetes Basics Lab for Backend Teams',
      description:
        'Guided lab for deploying backend services to Kubernetes, configuring health checks, and rolling updates.',
      dateTime: daysFromNow(28, 18),
      location: 'Kyiv Cloud Space',
      capacity: 50,
      isPublic: true,
      organizerEmail: 'denys@techevents.dev',
      participantEmails: [],
      tagSlugs: ['cloud', 'kubernetes', 'devops', 'docker', 'bootcamp'],
    },
    {
      id: 'seed-event-graphql-api-design',
      title: 'GraphQL API Design Session',
      description:
        'Best practices for schema design, resolver performance, and authorization in GraphQL APIs.',
      dateTime: daysFromNow(30, 19),
      location: 'Lviv Dev Center',
      capacity: 70,
      isPublic: true,
      organizerEmail: 'olena@techevents.dev',
      participantEmails: [
        'denys@techevents.dev',
        'max@techevents.dev',
        'iryna@techevents.dev',
        'viktor@techevents.dev',
        'anna@techevents.dev',
        'dmytro@techevents.dev',
        'sofiia@techevents.dev',
        'andriy@techevents.dev',
        'natalia@techevents.dev',
        'bohdan@techevents.dev',
      ],
      tagSlugs: ['technology', 'api-design', 'backend', 'web', 'meetup'],
    },
    {
      id: 'seed-event-frontend-testing-react',
      title: 'Frontend Testing in React: RTL + Vitest',
      description:
        'Practical workshop on reliable component and integration testing with modern frontend tooling.',
      dateTime: daysFromNow(33, 18),
      location: 'Odesa JS Meetup',
      capacity: 65,
      isPublic: true,
      organizerEmail: 'iryna@techevents.dev',
      participantEmails: [
        'olena@techevents.dev',
        'max@techevents.dev',
        'dmytro@techevents.dev',
      ],
      tagSlugs: ['web', 'react', 'frontend', 'education', 'workshop'],
    },
    {
      id: 'seed-event-highload-postgres-indexing',
      title: 'Highload PostgreSQL Indexing Strategies',
      description:
        'Deep dive into query plans, indexes, and practical tuning for large-scale transactional systems.',
      dateTime: daysFromNow(36, 17),
      location: 'Dnipro Data Community',
      capacity: 55,
      isPublic: true,
      organizerEmail: 'max@techevents.dev',
      participantEmails: [
        'olena@techevents.dev',
        'iryna@techevents.dev',
        'denys@techevents.dev',
        'viktor@techevents.dev',
        'anna@techevents.dev',
        'dmytro@techevents.dev',
        'sofiia@techevents.dev',
        'andriy@techevents.dev',
        'natalia@techevents.dev',
        'bohdan@techevents.dev',
        'larysa@techevents.dev',
        'kostiantyn@techevents.dev',
        'oksana@techevents.dev',
        'taras@techevents.dev',
        'halyna@techevents.dev',
        'yuriy@techevents.dev',
        'tetiana@techevents.dev',
        'mykola@techevents.dev',
        'olha@techevents.dev',
        'serhiy@techevents.dev',
      ],
      tagSlugs: ['data', 'postgresql', 'sql', 'backend', 'conference'],
    },
    {
      id: 'seed-event-ai-assistants-in-dev-workflow',
      title: 'AI Assistants in Daily Dev Workflow',
      description:
        'How engineering teams use AI tools for planning, coding, review, and documentation safely.',
      dateTime: daysFromNow(39, 19),
      location: 'Remote (Zoom)',
      capacity: 200,
      isPublic: true,
      organizerEmail: 'olena@techevents.dev',
      participantEmails: [],
      tagSlugs: ['technology', 'ai', 'llm', 'prompt-engineering', 'webinar'],
    },
    {
      id: 'seed-event-mobile-ci-cd-pipelines',
      title: 'Mobile CI/CD Pipelines with Fastlane',
      description:
        'Workshop on release automation for iOS and Android apps with signing, stores, and QA gates.',
      dateTime: daysFromNow(42, 18),
      location: 'Kharkiv Mobile Guild',
      capacity: 45,
      isPublic: true,
      organizerEmail: 'denys@techevents.dev',
      participantEmails: [
        'olena@techevents.dev',
        'max@techevents.dev',
        'iryna@techevents.dev',
        'viktor@techevents.dev',
        'anna@techevents.dev',
        'dmytro@techevents.dev',
        'sofiia@techevents.dev',
        'andriy@techevents.dev',
        'natalia@techevents.dev',
        'larysa@techevents.dev',
      ],
      tagSlugs: ['mobile', 'ios', 'android', 'ci-cd', 'workshop'],
    },
    {
      id: 'seed-event-observability-with-opentelemetry',
      title: 'Observability with OpenTelemetry',
      description:
        'Tracing, metrics, and logs end-to-end for microservices with practical OpenTelemetry setup.',
      dateTime: daysFromNow(45, 18),
      location: 'Kyiv SRE Hub',
      capacity: 85,
      isPublic: true,
      organizerEmail: 'max@techevents.dev',
      participantEmails: [
        'olena@techevents.dev',
        'iryna@techevents.dev',
        'denys@techevents.dev',
        'viktor@techevents.dev',
        'anna@techevents.dev',
        'dmytro@techevents.dev',
        'sofiia@techevents.dev',
        'andriy@techevents.dev',
        'natalia@techevents.dev',
        'larysa@techevents.dev',
      ],
      tagSlugs: ['devops', 'observability', 'microservices', 'cloud', 'meetup'],
    },
    {
      id: 'seed-event-open-source-mentoring-hour',
      title: 'Open Source Mentoring Hour',
      description:
        'Bring your repository and get live mentoring on issues, pull requests, and contribution workflows.',
      dateTime: daysFromNow(3, 19),
      location: 'Remote (Discord)',
      capacity: null,
      isPublic: true,
      organizerEmail: 'olena@techevents.dev',
      participantEmails: [
        'max@techevents.dev',
        'iryna@techevents.dev',
        'denys@techevents.dev',
      ],
      tagSlugs: [
        'community',
        'open-source',
        'mentoring',
        'networking',
        'meetup',
      ],
    },
    {
      id: 'seed-event-security-jwt-and-cookies',
      title: 'Security Clinic: JWT, Cookies, and Sessions',
      description:
        'Hands-on review of auth flows, token refresh patterns, and web security hardening techniques.',
      dateTime: daysFromNow(48, 19),
      location: 'Lviv Security Meetup',
      capacity: 75,
      isPublic: true,
      organizerEmail: 'iryna@techevents.dev',
      participantEmails: ['olena@techevents.dev', 'max@techevents.dev'],
      tagSlugs: ['security', 'authentication', 'jwt', 'oauth', 'workshop'],
    },
    {
      id: 'seed-event-python-data-engineering-intro',
      title: 'Intro to Python Data Engineering Pipelines',
      description:
        'Building robust ETL jobs with scheduling, validation, and monitoring for analytics teams.',
      dateTime: daysFromNow(51, 17),
      location: 'Remote (Google Meet)',
      capacity: 90,
      isPublic: true,
      organizerEmail: 'olena@techevents.dev',
      participantEmails: [],
      tagSlugs: [
        'data',
        'data-engineering',
        'python',
        'analytics',
        'education',
      ],
    },
    {
      id: 'seed-event-nodejs-performance-profiling',
      title: 'Node.js Performance Profiling Workshop',
      description:
        'Profiling CPU, memory, and event-loop bottlenecks in Node.js services and applying fixes.',
      dateTime: daysFromNow(54, 18),
      location: 'Kyiv Backend Club',
      capacity: 60,
      isPublic: true,
      organizerEmail: 'max@techevents.dev',
      participantEmails: [
        'olena@techevents.dev',
        'iryna@techevents.dev',
        'denys@techevents.dev',
        'viktor@techevents.dev',
        'anna@techevents.dev',
        'dmytro@techevents.dev',
        'sofiia@techevents.dev',
        'andriy@techevents.dev',
        'natalia@techevents.dev',
        'bohdan@techevents.dev',
        'larysa@techevents.dev',
        'kostiantyn@techevents.dev',
        'oksana@techevents.dev',
        'taras@techevents.dev',
        'halyna@techevents.dev',
        'yuriy@techevents.dev',
        'tetiana@techevents.dev',
        'mykola@techevents.dev',
        'olha@techevents.dev',
        'roman@techevents.dev',
        'vasyl@techevents.dev',
        'zhanna@techevents.dev',
      ],
      tagSlugs: [
        'technology',
        'node-js',
        'backend',
        'observability',
        'workshop',
      ],
    },
    {
      id: 'seed-event-microfrontends-architecture',
      title: 'Microfrontends Architecture Meetup',
      description:
        'Patterns, trade-offs, and deployment strategies for independent frontend teams at scale.',
      dateTime: daysFromNow(57, 19),
      location: 'Odesa Frontend Hub',
      capacity: 100,
      isPublic: true,
      organizerEmail: 'denys@techevents.dev',
      participantEmails: [
        'max@techevents.dev',
        'iryna@techevents.dev',
        'sofiia@techevents.dev',
      ],
      tagSlugs: [
        'web',
        'frontend',
        'software-architecture',
        'conference',
        'community',
      ],
    },
    {
      id: 'seed-event-go-concurrency-patterns',
      title: 'Go Concurrency Patterns in Practice',
      description:
        'Learn practical goroutine, channel, and worker-pool patterns for backend engineering tasks.',
      dateTime: daysFromNow(60, 18),
      location: 'Dnipro Golang Community',
      capacity: 50,
      isPublic: true,
      organizerEmail: 'iryna@techevents.dev',
      participantEmails: [],
      tagSlugs: ['technology', 'go', 'backend', 'system-design', 'workshop'],
    },
    {
      id: 'seed-event-product-analytics-for-engineers',
      title: 'Product Analytics for Engineers',
      description:
        'Designing events, funnels, and dashboards that help teams make better product decisions.',
      dateTime: daysFromNow(63, 18),
      location: 'Remote (Zoom)',
      capacity: 140,
      isPublic: true,
      organizerEmail: 'olena@techevents.dev',
      participantEmails: [
        'max@techevents.dev',
        'iryna@techevents.dev',
        'denys@techevents.dev',
        'viktor@techevents.dev',
        'anna@techevents.dev',
        'dmytro@techevents.dev',
        'sofiia@techevents.dev',
        'andriy@techevents.dev',
        'natalia@techevents.dev',
        'bohdan@techevents.dev',
      ],
      tagSlugs: ['product', 'analytics', 'bi', 'business', 'webinar'],
    },
    {
      id: 'seed-event-community-qa-office-hours',
      title: 'Community Q&A Office Hours',
      description:
        'Weekly open room for architecture questions, code review advice, and career mentoring for engineers.',
      dateTime: daysFromNow(64, 18),
      location: 'Remote (Google Meet)',
      capacity: null,
      isPublic: true,
      organizerEmail: 'max@techevents.dev',
      participantEmails: [],
      tagSlugs: ['community', 'mentoring', 'career', 'networking', 'meetup'],
    },
    {
      id: 'seed-event-event-driven-architecture',
      title: 'Event-Driven Architecture with Kafka',
      description:
        'Building asynchronous systems with Kafka, retries, idempotency, and consumer scaling.',
      dateTime: daysFromNow(66, 19),
      location: 'Kharkiv Streaming Lab',
      capacity: 70,
      isPublic: true,
      organizerEmail: 'max@techevents.dev',
      participantEmails: [
        'olena@techevents.dev',
        'iryna@techevents.dev',
        'denys@techevents.dev',
        'viktor@techevents.dev',
        'anna@techevents.dev',
        'dmytro@techevents.dev',
        'sofiia@techevents.dev',
        'andriy@techevents.dev',
        'natalia@techevents.dev',
        'bohdan@techevents.dev',
        'larysa@techevents.dev',
        'kostiantyn@techevents.dev',
        'oksana@techevents.dev',
        'taras@techevents.dev',
        'halyna@techevents.dev',
        'yuriy@techevents.dev',
        'tetiana@techevents.dev',
        'mykola@techevents.dev',
        'olha@techevents.dev',
        'fedir@techevents.dev',
      ],
      tagSlugs: [
        'technology',
        'microservices',
        'system-design',
        'backend',
        'conference',
      ],
    },
    {
      id: 'seed-event-cloud-cost-optimization',
      title: 'Cloud Cost Optimization for Startups',
      description:
        'Practical techniques to control infrastructure spending while keeping performance and reliability.',
      dateTime: daysFromNow(70, 18),
      location: 'Kyiv FinOps Meetup',
      capacity: 95,
      isPublic: true,
      organizerEmail: 'denys@techevents.dev',
      participantEmails: [],
      tagSlugs: ['cloud', 'finops', 'startup', 'business', 'webinar'],
    },
    {
      id: 'seed-event-jazz-and-code-rooftop',
      title: 'Jazz and Code Rooftop Session',
      description:
        'Evening meetup with a live jazz set, short talks about creative tooling, and networking between engineers and musicians.',
      dateTime: daysFromNow(72, 20),
      location: 'Lviv Roof Stage',
      capacity: 80,
      isPublic: true,
      organizerEmail: 'olha@techevents.dev',
      participantEmails: [
        'max@techevents.dev',
        'iryna@techevents.dev',
        'sofiia@techevents.dev',
        'andriy@techevents.dev',
        'roman@techevents.dev',
        'dariya@techevents.dev',
        'milena@techevents.dev',
        'zhanna@techevents.dev',
        'valentyna@techevents.dev',
      ],
      tagSlugs: ['music', 'live-music', 'community', 'networking', 'meetup'],
    },
    {
      id: 'seed-event-indie-film-screening-qa',
      title: 'Indie Film Screening and Director Q&A',
      description:
        'Community screening of short independent films followed by a practical Q&A on production and audience building.',
      dateTime: daysFromNow(74, 19),
      location: 'Kyiv Cinema Yard',
      capacity: 120,
      isPublic: true,
      organizerEmail: 'roman@techevents.dev',
      participantEmails: [
        'olena@techevents.dev',
        'sofiia@techevents.dev',
        'anna@techevents.dev',
        'dariya@techevents.dev',
        'milena@techevents.dev',
        'olha@techevents.dev',
        'zhanna@techevents.dev',
        'valentyna@techevents.dev',
      ],
      tagSlugs: ['film', 'cinema', 'art', 'community', 'meetup'],
    },
    {
      id: 'seed-event-digital-art-creative-coding-jam',
      title: 'Digital Art and Creative Coding Jam',
      description:
        'A live jam where artists and developers build browser-based visuals, experiment with motion, and share tools.',
      dateTime: daysFromNow(76, 19),
      location: 'Odesa Art Warehouse',
      capacity: 70,
      isPublic: true,
      organizerEmail: 'milena@techevents.dev',
      participantEmails: [
        'roman@techevents.dev',
        'dariya@techevents.dev',
        'olha@techevents.dev',
        'zhanna@techevents.dev',
        'max@techevents.dev',
        'sofiia@techevents.dev',
        'dmytro@techevents.dev',
        'vasyl@techevents.dev',
      ],
      tagSlugs: ['art', 'digital-art', 'creative-coding', 'web', 'community'],
    },
    {
      id: 'seed-event-startup-pitch-night-plus',
      title: 'Startup Pitch Night for Builders',
      description:
        'Founders, product people, and engineers pitch early-stage ideas, get feedback, and find teammates for next sprint.',
      dateTime: daysFromNow(78, 19),
      location: 'Dnipro Startup Garage',
      capacity: 90,
      isPublic: true,
      organizerEmail: 'max@techevents.dev',
      participantEmails: [
        'olena@techevents.dev',
        'denys@techevents.dev',
        'andriy@techevents.dev',
        'natalia@techevents.dev',
        'bohdan@techevents.dev',
        'kostiantyn@techevents.dev',
        'oksana@techevents.dev',
        'fedir@techevents.dev',
        'yaroslav@techevents.dev',
      ],
      tagSlugs: ['startup', 'pitching', 'business', 'networking', 'community'],
    },
    {
      id: 'seed-event-documentary-storytelling-workshop',
      title: 'Documentary Storytelling Workshop',
      description:
        'Practical workshop on documentary structure, interview preparation, and building a compelling narrative from real material.',
      dateTime: daysFromNow(80, 17),
      location: 'Dnipro Documentary House',
      capacity: 50,
      isPublic: true,
      organizerEmail: 'dariya@techevents.dev',
      participantEmails: [
        'roman@techevents.dev',
        'milena@techevents.dev',
        'olha@techevents.dev',
        'zhanna@techevents.dev',
        'valentyna@techevents.dev',
        'sofiia@techevents.dev',
        'andriy@techevents.dev',
      ],
      tagSlugs: [
        'film',
        'documentary',
        'screenwriting',
        'storytelling',
        'workshop',
      ],
    },
    {
      id: 'seed-event-electronic-music-production-lab',
      title: 'Electronic Music Production Lab',
      description:
        'A lab for producers and curious beginners on arranging, sound design, and collaborative production workflows.',
      dateTime: daysFromNow(82, 18),
      location: 'Kyiv Sound Lab',
      capacity: 45,
      isPublic: true,
      organizerEmail: 'zhanna@techevents.dev',
      participantEmails: [
        'roman@techevents.dev',
        'milena@techevents.dev',
        'dariya@techevents.dev',
        'olha@techevents.dev',
        'max@techevents.dev',
        'anna@techevents.dev',
        'sofiia@techevents.dev',
      ],
      tagSlugs: [
        'music',
        'music-production',
        'sound-design',
        'art',
        'workshop',
      ],
    },
    {
      id: 'seed-event-product-discovery-sprint-plus',
      title: 'Product Discovery Sprint',
      description:
        'A sprint-format workshop for startups on interviews, hypotheses, and finding the smallest next experiment worth running.',
      dateTime: daysFromNow(84, 10),
      location: 'Kyiv Product Studio',
      capacity: 50,
      isPublic: true,
      organizerEmail: 'olena@techevents.dev',
      participantEmails: [
        'max@techevents.dev',
        'iryna@techevents.dev',
        'denys@techevents.dev',
        'anna@techevents.dev',
        'sofiia@techevents.dev',
        'andriy@techevents.dev',
        'natalia@techevents.dev',
        'fedir@techevents.dev',
        'yaroslav@techevents.dev',
      ],
      tagSlugs: [
        'product',
        'product-discovery',
        'product-strategy',
        'startup',
        'workshop',
      ],
    },
    {
      id: 'seed-event-career-portfolio-lab-plus',
      title: 'Career Portfolio and Resume Lab',
      description:
        'A practical lab for engineers and creatives on sharpening portfolios, resumes, and the story they tell in interviews.',
      dateTime: daysFromNow(86, 17),
      location: 'Kyiv Career Lab',
      capacity: 55,
      isPublic: true,
      organizerEmail: 'sofiia@techevents.dev',
      participantEmails: [
        'olena@techevents.dev',
        'max@techevents.dev',
        'iryna@techevents.dev',
        'anna@techevents.dev',
        'dariya@techevents.dev',
        'roman@techevents.dev',
        'milena@techevents.dev',
        'andriy@techevents.dev',
        'tetiana@techevents.dev',
      ],
      tagSlugs: ['career', 'resume', 'branding', 'mentoring', 'education'],
    },
  ];
}
