import type { TagCatalogItem } from '@prisma-seed/types';

// Lower sortOrder means broader topic.
export const TAG_THEMES: TagCatalogItem[] = [
  { slug: 'technology', label: 'Technology', color: 'blue', sortOrder: 10 },
  { slug: 'business', label: 'Business', color: 'emerald', sortOrder: 11 },
  { slug: 'design', label: 'Design', color: 'yellow', sortOrder: 12 },
  { slug: 'data', label: 'Data', color: 'cyan', sortOrder: 13 },
  { slug: 'cloud', label: 'Cloud', color: 'sky', sortOrder: 14 },
  { slug: 'security', label: 'Security', color: 'red', sortOrder: 15 },
  { slug: 'devops', label: 'DevOps', color: 'indigo', sortOrder: 16 },
  { slug: 'product', label: 'Product', color: 'amber', sortOrder: 17 },
  { slug: 'mobile', label: 'Mobile', color: 'orange', sortOrder: 18 },
  { slug: 'web', label: 'Web', color: 'blue', sortOrder: 19 },
  { slug: 'community', label: 'Community', color: 'green', sortOrder: 20 },
  { slug: 'education', label: 'Education', color: 'green', sortOrder: 21 },
  { slug: 'career', label: 'Career', color: 'lime', sortOrder: 22 },
  { slug: 'leadership', label: 'Leadership', color: 'teal', sortOrder: 23 },
  { slug: 'startup', label: 'Startup', color: 'emerald', sortOrder: 24 },
  { slug: 'art', label: 'Art', color: 'rose', sortOrder: 25 },
  { slug: 'music', label: 'Music', color: 'rose', sortOrder: 26 },
  { slug: 'film', label: 'Film', color: 'slate', sortOrder: 27 },
];

type ThemeSlug = (typeof TAG_THEMES)[number]['slug'];

export const TAG_SUBTOPICS_BY_THEME: Record<ThemeSlug, TagCatalogItem[]> = {
  technology: [
    { slug: 'frontend', label: 'Frontend', color: 'orange', sortOrder: 100 },
    { slug: 'backend', label: 'Backend', color: 'indigo', sortOrder: 101 },
    {
      slug: 'software-architecture',
      label: 'Software Architecture',
      color: 'indigo',
      sortOrder: 102,
    },
    {
      slug: 'system-design',
      label: 'System Design',
      color: 'indigo',
      sortOrder: 103,
    },
    {
      slug: 'microservices',
      label: 'Microservices',
      color: 'indigo',
      sortOrder: 104,
    },
    {
      slug: 'api-design',
      label: 'API Design',
      color: 'blue',
      sortOrder: 105,
    },
    {
      slug: 'typescript',
      label: 'TypeScript',
      color: 'blue',
      sortOrder: 110,
    },
    {
      slug: 'javascript',
      label: 'JavaScript',
      color: 'orange',
      sortOrder: 111,
    },
    { slug: 'node-js', label: 'Node.js', color: 'green', sortOrder: 112 },
    { slug: 'nestjs', label: 'NestJS', color: 'red', sortOrder: 113 },
    { slug: 'react', label: 'React', color: 'sky', sortOrder: 114 },
    { slug: 'vue', label: 'Vue', color: 'emerald', sortOrder: 115 },
    { slug: 'angular', label: 'Angular', color: 'red', sortOrder: 116 },
    { slug: 'next-js', label: 'Next.js', color: 'slate', sortOrder: 117 },
    { slug: 'python', label: 'Python', color: 'yellow', sortOrder: 118 },
    { slug: 'go', label: 'Go', color: 'cyan', sortOrder: 119 },
    { slug: 'java', label: 'Java', color: 'orange', sortOrder: 120 },
    { slug: 'kotlin', label: 'Kotlin', color: 'purple', sortOrder: 121 },
    { slug: 'rust', label: 'Rust', color: 'orange', sortOrder: 122 },
    { slug: 'csharp', label: 'C#', color: 'indigo', sortOrder: 123 },
    { slug: 'php', label: 'PHP', color: 'purple', sortOrder: 124 },
    { slug: 'ai', label: 'AI', color: 'purple', sortOrder: 130 },
    {
      slug: 'machine-learning',
      label: 'Machine Learning',
      color: 'purple',
      sortOrder: 131,
    },
    { slug: 'llm', label: 'LLM', color: 'purple', sortOrder: 132 },
    { slug: 'mlops', label: 'MLOps', color: 'purple', sortOrder: 133 },
    {
      slug: 'prompt-engineering',
      label: 'Prompt Engineering',
      color: 'pink',
      sortOrder: 134,
    },
    {
      slug: 'computer-vision',
      label: 'Computer Vision',
      color: 'purple',
      sortOrder: 135,
    },
    { slug: 'nlp', label: 'NLP', color: 'purple', sortOrder: 136 },
  ],
  business: [
    {
      slug: 'product-management',
      label: 'Product Management',
      color: 'amber',
      sortOrder: 180,
    },
    { slug: 'growth', label: 'Growth', color: 'lime', sortOrder: 181 },
    { slug: 'marketing', label: 'Marketing', color: 'amber', sortOrder: 182 },
    { slug: 'sales', label: 'Sales', color: 'emerald', sortOrder: 183 },
    { slug: 'finops', label: 'FinOps', color: 'emerald', sortOrder: 184 },
  ],
  design: [
    { slug: 'ux-ui', label: 'UX/UI', color: 'yellow', sortOrder: 170 },
    {
      slug: 'accessibility',
      label: 'Accessibility',
      color: 'yellow',
      sortOrder: 171,
    },
    {
      slug: 'design-systems',
      label: 'Design Systems',
      color: 'yellow',
      sortOrder: 172,
    },
    { slug: 'branding', label: 'Branding', color: 'rose', sortOrder: 173 },
  ],
  data: [
    {
      slug: 'postgresql',
      label: 'PostgreSQL',
      color: 'blue',
      sortOrder: 140,
    },
    { slug: 'mysql', label: 'MySQL', color: 'sky', sortOrder: 141 },
    { slug: 'mongodb', label: 'MongoDB', color: 'green', sortOrder: 142 },
    { slug: 'redis', label: 'Redis', color: 'red', sortOrder: 143 },
    { slug: 'prisma', label: 'Prisma', color: 'indigo', sortOrder: 144 },
    { slug: 'sql', label: 'SQL', color: 'cyan', sortOrder: 145 },
    {
      slug: 'data-engineering',
      label: 'Data Engineering',
      color: 'cyan',
      sortOrder: 146,
    },
    { slug: 'analytics', label: 'Analytics', color: 'cyan', sortOrder: 147 },
    {
      slug: 'bi',
      label: 'Business Intelligence',
      color: 'teal',
      sortOrder: 148,
    },
  ],
  cloud: [
    { slug: 'docker', label: 'Docker', color: 'blue', sortOrder: 150 },
    {
      slug: 'kubernetes',
      label: 'Kubernetes',
      color: 'blue',
      sortOrder: 151,
    },
    { slug: 'terraform', label: 'Terraform', color: 'purple', sortOrder: 152 },
    { slug: 'aws', label: 'AWS', color: 'amber', sortOrder: 153 },
    { slug: 'gcp', label: 'GCP', color: 'sky', sortOrder: 154 },
    { slug: 'azure', label: 'Azure', color: 'blue', sortOrder: 155 },
    {
      slug: 'serverless',
      label: 'Serverless',
      color: 'orange',
      sortOrder: 156,
    },
  ],
  security: [
    {
      slug: 'appsec',
      label: 'Application Security',
      color: 'red',
      sortOrder: 160,
    },
    { slug: 'devsecops', label: 'DevSecOps', color: 'red', sortOrder: 161 },
    {
      slug: 'authentication',
      label: 'Authentication',
      color: 'red',
      sortOrder: 162,
    },
    { slug: 'oauth', label: 'OAuth', color: 'red', sortOrder: 163 },
    { slug: 'jwt', label: 'JWT', color: 'red', sortOrder: 164 },
    { slug: 'owasp', label: 'OWASP', color: 'red', sortOrder: 165 },
  ],
  devops: [
    { slug: 'ci-cd', label: 'CI/CD', color: 'indigo', sortOrder: 157 },
    {
      slug: 'observability',
      label: 'Observability',
      color: 'teal',
      sortOrder: 158,
    },
  ],
  product: [
    {
      slug: 'product-strategy',
      label: 'Product Strategy',
      color: 'amber',
      sortOrder: 205,
    },
    {
      slug: 'product-discovery',
      label: 'Product Discovery',
      color: 'amber',
      sortOrder: 206,
    },
    {
      slug: 'experiment-design',
      label: 'Experiment Design',
      color: 'amber',
      sortOrder: 207,
    },
  ],
  mobile: [
    { slug: 'ios', label: 'iOS', color: 'slate', sortOrder: 208 },
    { slug: 'android', label: 'Android', color: 'green', sortOrder: 209 },
    {
      slug: 'react-native',
      label: 'React Native',
      color: 'sky',
      sortOrder: 210,
    },
    { slug: 'flutter', label: 'Flutter', color: 'cyan', sortOrder: 211 },
  ],
  web: [
    {
      slug: 'frontend-performance',
      label: 'Frontend Performance',
      color: 'blue',
      sortOrder: 212,
    },
    {
      slug: 'web-platform',
      label: 'Web Platform',
      color: 'sky',
      sortOrder: 213,
    },
    { slug: 'pwa', label: 'PWA', color: 'blue', sortOrder: 214 },
  ],
  community: [
    { slug: 'mentoring', label: 'Mentoring', color: 'green', sortOrder: 190 },
    {
      slug: 'networking',
      label: 'Networking',
      color: 'green',
      sortOrder: 191,
    },
    {
      slug: 'open-source',
      label: 'Open Source',
      color: 'green',
      sortOrder: 192,
    },
    { slug: 'workshop', label: 'Workshop', color: 'teal', sortOrder: 193 },
    { slug: 'meetup', label: 'Meetup', color: 'teal', sortOrder: 194 },
    {
      slug: 'conference',
      label: 'Conference',
      color: 'teal',
      sortOrder: 195,
    },
    { slug: 'webinar', label: 'Webinar', color: 'teal', sortOrder: 196 },
    { slug: 'hackathon', label: 'Hackathon', color: 'teal', sortOrder: 197 },
  ],
  education: [
    { slug: 'bootcamp', label: 'Bootcamp', color: 'green', sortOrder: 215 },
    {
      slug: 'masterclass',
      label: 'Masterclass',
      color: 'green',
      sortOrder: 216,
    },
    {
      slug: 'storytelling',
      label: 'Storytelling',
      color: 'green',
      sortOrder: 217,
    },
  ],
  career: [
    {
      slug: 'interviewing',
      label: 'Interviewing',
      color: 'lime',
      sortOrder: 200,
    },
    { slug: 'resume', label: 'Resume', color: 'lime', sortOrder: 201 },
    {
      slug: 'freelancing',
      label: 'Freelancing',
      color: 'lime',
      sortOrder: 202,
    },
    {
      slug: 'remote-work',
      label: 'Remote Work',
      color: 'slate',
      sortOrder: 203,
    },
    {
      slug: 'team-management',
      label: 'Team Management',
      color: 'teal',
      sortOrder: 204,
    },
  ],
  leadership: [
    {
      slug: 'engineering-management',
      label: 'Engineering Management',
      color: 'teal',
      sortOrder: 218,
    },
    {
      slug: 'facilitation',
      label: 'Facilitation',
      color: 'teal',
      sortOrder: 219,
    },
    { slug: 'coaching', label: 'Coaching', color: 'teal', sortOrder: 220 },
  ],
  startup: [
    { slug: 'pitching', label: 'Pitching', color: 'emerald', sortOrder: 221 },
    {
      slug: 'fundraising',
      label: 'Fundraising',
      color: 'emerald',
      sortOrder: 222,
    },
    {
      slug: 'operations',
      label: 'Operations',
      color: 'emerald',
      sortOrder: 223,
    },
  ],
  art: [
    {
      slug: 'digital-art',
      label: 'Digital Art',
      color: 'rose',
      sortOrder: 224,
    },
    {
      slug: 'illustration',
      label: 'Illustration',
      color: 'pink',
      sortOrder: 225,
    },
    {
      slug: 'photography',
      label: 'Photography',
      color: 'rose',
      sortOrder: 226,
    },
    {
      slug: 'creative-coding',
      label: 'Creative Coding',
      color: 'purple',
      sortOrder: 227,
    },
  ],
  music: [
    {
      slug: 'live-music',
      label: 'Live Music',
      color: 'rose',
      sortOrder: 228,
    },
    {
      slug: 'music-production',
      label: 'Music Production',
      color: 'purple',
      sortOrder: 229,
    },
    {
      slug: 'sound-design',
      label: 'Sound Design',
      color: 'purple',
      sortOrder: 230,
    },
    { slug: 'dj', label: 'DJ', color: 'pink', sortOrder: 231 },
  ],
  film: [
    { slug: 'cinema', label: 'Cinema', color: 'slate', sortOrder: 232 },
    {
      slug: 'documentary',
      label: 'Documentary',
      color: 'slate',
      sortOrder: 233,
    },
    {
      slug: 'screenwriting',
      label: 'Screenwriting',
      color: 'amber',
      sortOrder: 234,
    },
    {
      slug: 'animation',
      label: 'Animation',
      color: 'pink',
      sortOrder: 235,
    },
  ],
};

export const TAG_CATALOG: TagCatalogItem[] = [
  ...TAG_THEMES,
  ...Object.values(TAG_SUBTOPICS_BY_THEME).flat(),
];
